#!/bin/bash
# SPDX-License-Identifier: AGPL-3.0-only
#
# Idempotent installer for the qnop demo host. Run as root (user-data does).
#
# - copies the demo stack to /opt/qnop-demo (scripts + compose, never .env
#   or golden/, so re-running after a `git pull` only refreshes the code)
# - generates /opt/qnop-demo/.env with random secrets on first run
# - installs the 12-hourly reset cron job
# - starts (or updates) the stack
set -euo pipefail

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEST=/opt/qnop-demo

mkdir -p "$DEST/golden"
install -m 0755 "$SRC/reset-demo.sh" "$SRC/build-golden-state.sh" "$SRC/stage-demo-settings.sh" "$DEST/"
install -m 0644 "$SRC/docker-compose.yml" "$SRC/Caddyfile" "$DEST/"

if [ ! -f "$DEST/.env" ]; then
  umask 077
  cat > "$DEST/.env" <<EOF
# Generated by install.sh on first boot — demo-instance secrets.
QNOP_DEMO_DOMAIN=demo.qnop.io
QNOP_DEMO_ACME_EMAIL=info@devtank42.de
QNOP_VERSION=latest
QNOP_DB_NAME=qnop
QNOP_DB_USERNAME=qnop
QNOP_DB_PASSWORD=$(openssl rand -hex 24)
QNOP_S3_BUCKET=qnop-documents
QNOP_S3_ACCESS_KEY=qnop-demo
QNOP_S3_SECRET_KEY=$(openssl rand -hex 24)
QNOP_AUTH_JWT_SECRET=$(openssl rand -base64 48 | tr -d '\n')
QNOP_AUTH_ENCRYPTION_KEY=$(openssl rand -base64 48 | tr -d '\n')
QNOP_AUTH_ENCRYPTION_SALT=$(openssl rand -hex 32)

# Demo staging (stage-demo-settings.sh) — host-only secrets, never committed.
# The rotated password of the 'admin' account:
DEMO_ADMIN_PASSWORD=$(openssl rand -base64 18 | tr -d '\n')
# Private Umami instance for usage tracking; leave empty to skip:
DEMO_TRACKING_HOST=
DEMO_TRACKING_SITE_ID=
EOF
  umask 022
  echo "Wrote fresh secrets to $DEST/.env"
fi

# Reset + redeploy twice a day; the job pulls the latest images first, so
# every qnop release rolls out automatically with the next reset.
cat > /etc/cron.d/qnop-demo-reset <<'EOF'
0 3,15 * * * root /opt/qnop-demo/reset-demo.sh >> /var/log/qnop-demo-reset.log 2>&1
EOF
chmod 0644 /etc/cron.d/qnop-demo-reset

cd "$DEST"
docker compose pull
docker compose up -d
echo "qnop demo stack is up. Next: stage the demo content, then run build-golden-state.sh"
